package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/adity1raut/hiver-support-agent/internal/agent"
	"github.com/adity1raut/hiver-support-agent/internal/eval"
	"github.com/adity1raut/hiver-support-agent/internal/taxonomy"
)

func renderMarkdown(rep Report, items []goldenItem, outsBySystem map[string][]agent.Output, judgeBy map[string]eval.JudgeScore) string {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	w("# Results — Delta Twitter support agent")
	w("")
	w("Generated by `go run ./cmd/report`. Every number here is reproduced by `make repro`.")
	w("")

	g := rep.GoldenSet
	w("## 1. The evaluation set")
	w("")
	w("%d labelled messages drawn from the **eval pool** — the most recent 30%% of Delta's", g.N)
	w("episodes, which the retrieval index never sees.")
	w("")
	if g.Reviewed == 0 {
		w("> ⚠️ **These labels have NOT been through human review.** They are model drafts from")
		w("> `cmd/label-assist` (two independent passes plus adjudication). Every accuracy number")
		w("> below is therefore measured against labels produced by the same family of model being")
		w("> evaluated, and is inflated by an unknown amount. Run `make review` to adjudicate them,")
		w("> then `make report` again — this warning disappears and §6 gains a real agreement number.")
		w("")
	} else if g.Reviewed < g.N {
		w("> ⚠️ **Partial human review: %d of %d items.** The rest are model drafts.", g.Reviewed, g.N)
		w("")
	}
	w("| | count |")
	w("|---|---|")
	for _, s := range sortedKeys(g.ByStratum) {
		w("| stratum `%s` | %d |", s, g.ByStratum[s])
	}
	w("| human-reviewed | %d |", g.Reviewed)
	w("| human overrode the draft label | %d (%s) |", g.Overridden, pct(safeDiv(g.Overridden, g.Reviewed)))
	w("| two annotation passes agreed unaided | %s |", pct(g.TwoPassAgreement))
	w("")
	w("Intent distribution (gold):")
	w("")
	w("| intent | n | share |")
	w("|---|---:|---:|")
	for _, name := range taxonomy.Names() {
		if g.IntentCounts[name] == 0 {
			continue
		}
		w("| `%s` | %d | %s |", name, g.IntentCounts[name], pct(float64(g.IntentCounts[name])/float64(g.N)))
	}
	w("")
	w("Route distribution: **auto %d / escalate %d** overall; in the unbiased `random`",
		g.RouteCounts["auto"], g.RouteCounts["escalate"])
	w("stratum alone it is **auto %d / escalate %d**. The targeted stratum is deliberately",
		g.RandomRouteCounts["auto"], g.RandomRouteCounts["escalate"])
	w("escalation-heavy and must never be read as a traffic estimate.")
	w("")

	w("## 2. Intent classification")
	w("")
	w("| system | accuracy | 95%% CI | macro-F1 | 95%% CI | accuracy (random stratum) |")
	w("|---|---:|---:|---:|---:|---:|")
	for _, s := range rep.Systems {
		if s.Intent.N == 0 {
			continue
		}
		w("| `%s` | %s | %s | %.3f | %s | %s |", s.Name, pct(s.Intent.Accuracy), ci(s.AccuracyCI),
			s.Intent.MacroF1, ci(s.MacroF1CI), pct(s.IntentRandom.Accuracy))
	}
	w("")
	w("Per-class F1 for the agent:")
	w("")
	if m, ok := findSystem(rep.Systems, "agent"); ok {
		w("| intent | support | precision | recall | F1 |")
		w("|---|---:|---:|---:|---:|")
		for _, c := range m.Intent.PerClass {
			if c.Support == 0 {
				continue
			}
			w("| `%s` | %d | %.2f | %.2f | %.2f |", c.Label, c.Support, c.Precision, c.Recall, c.F1)
		}
		w("")
		w("Confusion matrix (rows = gold, columns = predicted), classes with any mass:")
		w("")
		w("```")
		w("%s", confusionASCII(m.Intent))
		w("```")
		w("")
	}

	w("## 3. Routing: auto-handle vs escalate")
	w("")
	w("`escalate` is the positive class. The number that matters operationally is")
	w("**false-auto rate** — of the messages a system handled without a human, how many")
	w("actually needed one. Auto rate is the value; false-auto is the bill.")
	w("")
	w("| system | auto rate | false-auto rate | 95%% CI | escalation recall | over-escalation | routing acc |")
	w("|---|---:|---:|---:|---:|---:|---:|")
	for _, s := range rep.Systems {
		if s.Routing.N == 0 {
			continue
		}
		r := s.Routing
		w("| `%s` | %s | **%s** | %s | %s | %s | %s |", s.Name, pct(r.AutoRate), pct(r.FalseAutoRate),
			ci(r.FalseAutoCI), pct(r.EscalationRecall), pct(r.OverEscalation), pct(r.Accuracy))
	}
	w("")
	w("Same table on the **random stratum only** — this is the honest estimate of live behaviour:")
	w("")
	w("| system | auto rate | false-auto rate | 95%% CI | escalation recall |")
	w("|---|---:|---:|---:|---:|")
	for _, s := range rep.Systems {
		if s.RoutingRandom.N == 0 {
			continue
		}
		r := s.RoutingRandom
		w("| `%s` | %s | **%s** | %s | %s |", s.Name, pct(r.AutoRate), pct(r.FalseAutoRate),
			ci(r.FalseAutoCI), pct(r.EscalationRecall))
	}
	w("")

	w("## 4. Reply quality (LLM judge)")
	w("")
	w("Scores are 1-5. `composite` = 0.5·grounding + 0.3·resolution + 0.2·tone.")
	w("`sendable` is the judge's ship/no-ship call. **auto-sendable** restricts that to")
	w("replies the system would actually have sent unattended — the only column that")
	w("describes what a customer would really receive.")
	w("")
	w("| system | n | grounding | resolution | tone | composite | 95%% CI | sendable | auto-sendable | violations |")
	w("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
	for _, s := range rep.Systems {
		j := s.Judge
		if j.N == 0 {
			continue
		}
		as := "—"
		if j.AutoSendableN > 0 {
			as = fmt.Sprintf("%s (n=%d)", pct(j.AutoSendable), j.AutoSendableN)
		}
		w("| `%s` | %d | %.2f | %.2f | %.2f | %.2f | [%.2f-%.2f] | %s | %s | %s |",
			s.Name, j.N, j.Grounding, j.Resolution, j.Tone, j.Composite,
			j.CompositeCI[0], j.CompositeCI[1], pct(j.SendableRate), as, pct(j.ViolationRate))
	}
	w("")

	w("## 5. Does the judge agree with a human?")
	w("")
	if st, ok := rep.JudgeAgreement["status"]; ok {
		w("> %v", st)
		w("")
	} else {
		w("A human graded a blind sample of replies on the same rubric, without seeing")
		w("either the system name or the judge's scores.")
		w("")
		w("| dimension | n | exact | within 1 | MAE | quadratic κ | Spearman | judge bias |")
		w("|---|---:|---:|---:|---:|---:|---:|---:|")
		for _, dim := range []string{"grounding", "resolution", "tone"} {
			if o, ok := rep.JudgeAgreement[dim].(eval.OrdinalAgreement); ok {
				w("| %s | %d | %s | %s | %.2f | %.3f | %.3f | %+.2f |", dim, o.N,
					pct(o.ExactAgreement), pct(o.Within1), o.MAE, o.QuadraticKappa, o.Spearman, o.Bias)
			}
		}
		w("")
		w("Ship/no-ship call: agreement %v, Cohen's κ %v.",
			fmtAny(rep.JudgeAgreement["sendable_agreement"]), fmtAny(rep.JudgeAgreement["sendable_kappa"]))
		w("")
	}

	w("## 6. How good are the gold labels?")
	w("")
	lq := rep.LabelQuality
	w("| measure | value |")
	w("|---|---:|")
	w("| items human-reviewed | %v |", fmtAny(lq["reviewed"]))
	w("| human overrode the model draft | %v (%v) |", fmtAny(lq["overridden"]), fmtPct(lq["override_rate"]))
	w("| anchored intent agreement / κ | %v / %v |", fmtPct(lq["anchored_intent_agreement"]), fmtAny(lq["anchored_intent_kappa"]))
	w("| anchored route agreement / κ | %v / %v |", fmtPct(lq["anchored_route_agreement"]), fmtAny(lq["anchored_route_kappa"]))
	if _, ok := lq["blind_audit_n"]; ok {
		w("| **blind** audit n | %v |", fmtAny(lq["blind_audit_n"]))
		w("| **blind** intent agreement / κ | %v / %v |", fmtPct(lq["blind_intent_agreement"]), fmtAny(lq["blind_intent_kappa"]))
		w("| **blind** route agreement / κ | %v / %v |", fmtPct(lq["blind_route_agreement"]), fmtAny(lq["blind_route_kappa"]))
	} else {
		w("| blind audit | not run — `go run ./cmd/review -mode audit` |")
	}
	w("")
	if _, ok := lq["reviewed"]; !ok || fmtAny(lq["reviewed"]) == "0" {
		w("")
		w("**No human review has been run.** The golden labels are model drafts, so there is")
		w("currently no evidence at all about their quality — the table above is empty by")
		w("construction, not by accident. Until `make review` and `make audit` are run, treat")
		w("every accuracy figure in this report as an upper bound.")
	} else {
		w("")
		w("The anchored numbers are inflated by construction: the reviewer saw the draft.")
		w("The blind audit is the one to trust.")
	}
	w("")

	w("## 7. What the guardrails buy")
	w("")
	if wr, ok := rep.Ablations["routing_with_guardrails"].(eval.Routing); ok {
		mo := rep.Ablations["routing_model_only"].(eval.Routing)
		w("| routing policy | auto rate | false-auto rate | escalation recall |")
		w("|---|---:|---:|---:|")
		w("| model's own judgement alone | %s | **%s** | %s |", pct(mo.AutoRate), pct(mo.FalseAutoRate), pct(mo.EscalationRecall))
		w("| + deterministic guardrails (shipped) | %s | **%s** | %s |", pct(wr.AutoRate), pct(wr.FalseAutoRate), pct(wr.EscalationRecall))
		w("")
		w("The guardrails flipped %v model `auto` decisions to `escalate`.", fmtAny(rep.Ablations["guardrail_overrides"]))
		w("")
	}
	if rules, ok := rep.Ablations["rule_firing"]; ok {
		w("Which guardrails actually fire, and how often the gold label agreed that the")
		w("message needed a human (`precision`):")
		w("")
		w("| rule | fired | precision |")
		w("|---|---:|---:|")
		for _, r := range asRuleRows(rules) {
			w("| `%s` | %d | %.2f |", r.Rule, r.Fired, r.Precision)
		}
		w("")
	}

	if len(rep.Calibration) > 0 {
		w("## 8. Is the agent's confidence meaningful?")
		w("")
		w("The agent reports its own intent confidence and the routing policy uses it as a")
		w("threshold. If it is not calibrated, that threshold is decoration.")
		w("")
		w("| confidence bucket | n | mean confidence | actual accuracy |")
		w("|---|---:|---:|---:|")
		for _, c := range rep.Calibration {
			if c.N == 0 {
				continue
			}
			w("| %.2f–%.2f | %d | %.3f | %s |", c.Lo, c.Hi, c.N, c.MeanConf, pct(c.Accuracy))
		}
		w("")
	}

	w("## 9. Failure gallery")
	w("")
	w(failureGallery(items, outsBySystem, judgeBy))

	return b.String()
}

type ruleRow struct {
	Rule      string  `json:"rule"`
	Fired     int     `json:"fired"`
	Precision float64 `json:"precision"`
}

func asRuleRows(v any) []ruleRow {
	rs, _ := v.([]ruleRow)
	return rs
}

// failureGallery pulls quotable failures out of the agent's run.
func failureGallery(items []goldenItem, outsBySystem map[string][]agent.Output, judgeBy map[string]eval.JudgeScore) string {
	outs, ok := outsBySystem["agent"]
	if !ok {
		return "_(no agent run to analyse)_"
	}
	byID := map[string]goldenItem{}
	for _, g := range items {
		byID[g.EpisodeID] = g
	}
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	section := func(title, note string, pick func(agent.Output, goldenItem, eval.JudgeScore) bool, limit int) {
		w("### %s", title)
		w("")
		w("%s", note)
		w("")
		n := 0
		for _, o := range outs {
			g, ok := byID[o.EpisodeID]
			if !ok {
				continue
			}
			js := judgeBy["agent|"+o.EpisodeID]
			if !pick(o, g, js) {
				continue
			}
			n++
			w("**`%s`** (gold `%s`/`%s`, predicted `%s`/`%s`)", o.EpisodeID, g.GoldIntent, g.GoldRoute, o.Intent, o.Route)
			w("")
			w("> %s", oneLine(g.CustomerText))
			w("")
			w("agent replied: _%s_", oneLine(o.Reply))
			if js.Rationale != "" {
				w("")
				w("judge (g%d/r%d/t%d): %s", js.Grounding, js.Resolution, js.Tone, oneLine(js.Rationale))
			}
			w("")
			if n >= limit {
				break
			}
		}
		if n == 0 {
			w("_none in this run_")
			w("")
		}
	}

	section("F1 — auto-handled something that needed a human",
		"The expensive failure. Every row here is a customer who got a bot when they needed an agent.",
		func(o agent.Output, g goldenItem, _ eval.JudgeScore) bool {
			return g.GoldRoute == "escalate" && o.Route == agent.RouteAuto
		}, 5)

	section("F2 — ungrounded reply (judge grounding ≤ 2)",
		"The reply asserts something the message does not support.",
		func(o agent.Output, _ goldenItem, js eval.JudgeScore) bool {
			return js.N() && js.Grounding <= 2
		}, 5)

	section("F3 — intent confusion with high confidence",
		"Wrong label, and confident about it. These are the ones a confidence threshold cannot catch.",
		func(o agent.Output, g goldenItem, _ eval.JudgeScore) bool {
			return o.Intent != g.GoldIntent && o.Confidence >= 0.9
		}, 5)

	section("F4 — escalated something a reply would have solved",
		"The cheap failure, but it is what caps the business case.",
		func(o agent.Output, g goldenItem, _ eval.JudgeScore) bool {
			return g.GoldRoute == "auto" && o.Route == agent.RouteEscalate
		}, 5)

	section("F5 — no usable precedent",
		"Retrieval found nothing close, so the reply falls back to generic brand voice.",
		func(o agent.Output, _ goldenItem, _ eval.JudgeScore) bool {
			return o.RetrievalTop < 0.12
		}, 4)

	return b.String()
}

func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.TrimSpace(s)
	if len([]rune(s)) > 240 {
		s = string([]rune(s)[:240]) + "…"
	}
	return s
}

func confusionASCII(c eval.Classification) string {
	var present []int
	for i, l := range c.Labels {
		_ = l
		sum := 0
		for j := range c.Labels {
			sum += c.Confusion[i][j] + c.Confusion[j][i]
		}
		if sum > 0 {
			present = append(present, i)
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "%-22s", "gold \\ pred")
	for _, j := range present {
		fmt.Fprintf(&b, "%5s", short(c.Labels[j]))
	}
	b.WriteString("\n")
	for _, i := range present {
		fmt.Fprintf(&b, "%-22s", c.Labels[i])
		for _, j := range present {
			v := c.Confusion[i][j]
			if v == 0 {
				fmt.Fprintf(&b, "%5s", ".")
			} else {
				fmt.Fprintf(&b, "%5d", v)
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("\nkey: ")
	for _, j := range present {
		fmt.Fprintf(&b, "%s=%s  ", short(c.Labels[j]), c.Labels[j])
	}
	return b.String()
}

func short(s string) string {
	parts := strings.Split(s, "_")
	out := ""
	for _, p := range parts {
		if p != "" {
			out += strings.ToUpper(p[:1])
		}
	}
	if len(out) > 4 {
		out = out[:4]
	}
	return out
}

func findSystem(ss []SystemMetrics, name string) (SystemMetrics, bool) {
	for _, s := range ss {
		if s.Name == name {
			return s, true
		}
	}
	return SystemMetrics{}, false
}

func sortedKeys(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func safeDiv(a, b int) float64 {
	if b == 0 {
		return 0
	}
	return float64(a) / float64(b)
}

func fmtAny(v any) string {
	if v == nil {
		return "—"
	}
	switch t := v.(type) {
	case float64:
		return fmt.Sprintf("%.3f", t)
	case int:
		return fmt.Sprintf("%d", t)
	}
	return fmt.Sprintf("%v", v)
}

func fmtPct(v any) string {
	if f, ok := v.(float64); ok {
		return pct(f)
	}
	return "—"
}
