// Command gen-docs renders docs/ANNOTATION_GUIDE.md from the taxonomy and rubric
// source, so the docs cannot drift from the rules the annotator was given.
//
//	go run ./cmd/gen-docs
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/adity1raut/hiver-support-agent/internal/eval"
	"github.com/adity1raut/hiver-support-agent/internal/taxonomy"
)

func main() {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	w("<!-- GENERATED by `go run ./cmd/gen-docs` - edit internal/taxonomy and internal/eval instead. -->")
	w("")
	w("# Annotation guide")
	w("")
	w("How the golden set was sampled and labelled, and the rubric the judge uses.")
	w("")
	w("## Sampling")
	w("")
	w("Source: Delta episodes extracted from the TWCS corpus (`cmd/build-dataset`). An")
	w("*episode* is a conversation thread rooted at an inbound customer tweet in which")
	w("Delta replied at least once. 25,685 such episodes exist.")
	w("")
	w("The corpus is split **temporally**, not randomly: the earliest 70%% becomes the")
	w("history the agent may retrieve from, the latest 30%% becomes the eval pool. Delta's")
	w("volume is concentrated in Oct-Dec 2017, and mass-disruption days produce near-identical")
	w("tweets minutes apart; a random split would let the agent retrieve a twin of the very")
	w("message it is being tested on.")
	w("")
	w("From the eval pool we drop messages under 25 characters, messages with no alphabetic")
	w("content, and exact token-level duplicates. 200 items are then drawn in two strata:")
	w("")
	w("| stratum | n | how | what it measures |")
	w("|---|---:|---|---|")
	w("| `random` | 120 | uniform draw | unbiased estimate of live performance on Delta's real inbound mix |")
	w("| `targeted` | 80 | round-robin over each escalation guardrail's matches, then over 20 k-means topical clusters | whether the system breaks where breaking is expensive |")
	w("")
	w("**The two strata are never pooled for a headline claim.** The targeted stratum is")
	w("escalation-heavy by construction, so pooled numbers overstate how hard live traffic is.")
	w("")
	w("## Labelling protocol")
	w("")
	w("Each item carries two labels: an `intent` and a `route` (auto / escalate).")
	w("")
	w("1. **Two independent draft passes.** Pass A reasons top-down from the taxonomy;")
	w("   pass B reasons bottom-up from what the customer needs. Neither sees the other.")
	w("   Both see the **full thread**, including Delta's actual replies and whether the")
	w("   customer came back unhappy - oracle information the system under test never gets.")
	w("2. **Adjudication.** Where the passes disagree, a third pass sees both answers and decides.")
	w("3. **Human review** (`go run ./cmd/review -mode labels`). Every item is shown to a")
	w("   human with its draft label; the human confirms or overrides. Override rate is reported.")
	w("4. **Blind audit** (`go run ./cmd/review -mode audit`). A random subset is re-labelled")
	w("   by the human with the draft hidden. Step 3 is anchored and understates disagreement;")
	w("   this step is the unbiased estimate of draft-label quality.")
	w("")
	w("## Intent taxonomy")
	w("")
	w("Derived from k-means clustering of 6,000 historical customer messages")
	w("(`cmd/discover-intents`, raw output in `reports/intent_clusters.json`), then merged")
	w("by hand. The organising principle is **what the support desk does next**, not topic")
	w("similarity: two messages share an intent when they route to the same queue and need")
	w("the same information from the customer.")
	w("")
	for i, in := range taxonomy.Intents {
		w("### %d. `%s`", i+1, in.Name)
		w("")
		w("%s", in.Description)
		w("")
		w("- **include**: %s", in.Includes)
		w("- **exclude**: %s", in.Excludes)
		w("- **default handling**: %s", in.DefaultAction)
		w("")
	}
	w("## Route labelling rule")
	w("")
	w("```")
	w("%s", taxonomy.RoutePolicy)
	w("```")
	w("")
	w("## Reply-quality rubric (LLM judge and human raters use the same one)")
	w("")
	w("```")
	w("%s", eval.JudgeRubric)
	w("```")
	w("")
	w("The judge sees the customer tweet, the draft reply, and Delta's actual reply as")
	w("*one acceptable answer among many*. It is told explicitly that Delta's own replies")
	w("are often lazy deflections that would score poorly, because otherwise it collapses")
	w("into a similarity metric against a weak reference.")
	w("")
	w("The judge never sees which system wrote the reply. Humans rating the same replies")
	w("(`cmd/review -mode replies`) see neither the system nor the judge's scores.")

	if err := os.WriteFile("docs/ANNOTATION_GUIDE.md", []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("wrote docs/ANNOTATION_GUIDE.md")
}
